---
language: go
go:
  - "1.11"

install:
  - go get -v github.com/golang/dep/cmd/dep golang.org/x/tools/cmd/cover github.com/mattn/goveralls
  - dep ensure -v -vendor-only

script:
  - go test -v -covermode=count -coverprofile=coverage.out

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

notifications:
  email: false

# vim: set ts=2 sw=2 et:
